services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    restart: always
    networks:
      - traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --providers.docker
      - --log.level=ERROR
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.email=SEU_EMAIL # Preencha com SEU email
      - --certificatesresolvers.leresolver.acme.storage=./acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/docker/traefik/acme.json:/acme.json"
    labels:
      # Configuração default traefik
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Configurando o traefik para o proprio traefik
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.SEU_DOMINIO`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      # Abaixo preencher o acesso criado pelo apache no formato admin:(senha)
      - "traefik.http.middlewares.auth.basicauth.users=SENHA_CRIPTOGRAFADA_APACHE" #OBS onde tiver "$" colocar dois "$$"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.27.0-rc2-alpine # Imagem ao seu gosto
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - traefik
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/portainer/data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.SEU_DOMINIO`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.SEU_DOMINIO`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik"

volumes:
  portainer_data:

networks:
  traefik:
    external: true
