services:
  budibase:
    image: budibase/budibase
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.budibase.rule=Host(`budibase.SEU_DOMINIO`)"
      - "traefik.http.routers.budibase.tls.certresolver=leresolver"
      - "traefik.http.services.budibase.loadbalancer.server.port=5678" # 5678 é a porta padrão que o n8n atende
      - "traefik.http.routers.budibase.entrypoints=websecure"
      - "traefik.http.routers.budibase.service=budibase"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
